cmake_minimum_required(VERSION 3.16)
project(examples_2d LANGUAGES CXX)



add_subdirectory( ex2d_sample )

add_subdirectory( ex2d_property )
# add_subdirectory( ex2d_fails ) X
add_subdirectory( ex2d_timer )
add_subdirectory( ex2d_paths )
add_subdirectory( ex2d_assets )
add_subdirectory( ex2d_motions )
add_subdirectory( ex2d_position )
add_subdirectory( ex2d_velocity )
add_subdirectory( ex2d_reactive )
add_subdirectory( ex2d_camera )
add_subdirectory( ex2d_gradients )
add_subdirectory( ex2d_rounded )
add_subdirectory( ex2d_canvas_paths )

add_subdirectory( ex2d_texts )
add_subdirectory( ex2d_images )
add_subdirectory( ex2d_flexLayout )
add_subdirectory( ex2d_mouse )
add_subdirectory( ex2d_keys )
add_subdirectory( ex2d_inputs )
add_subdirectory( ex2d_sml )
add_subdirectory( ex2d_openmp_check )
add_subdirectory( ex2d_z_sorting )


