cmake_minimum_required(VERSION 3.16)
project(examples_3d LANGUAGES CXX)



# add_subdirectory( ex3d_ecs ) ## OK
# add_subdirectory( ex3d_ecs_boids ) ## X
# add_subdirectory( ex3d_ecs_collisions ) ## OK


# add_subdirectory( ex3d_ecs_rendering_static_count ) ## OK
# add_subdirectory( ex3d_ecs_rendering_dynamic_count ) ## OK

# add_subdirectory( ex3d_collision_tree ) ## OK
# add_subdirectory( ex3d_camera_controls ) ## OK
# add_subdirectory( ex3d_circle ) ## OK
# add_subdirectory( ex3d_circles ) ## OK
# add_subdirectory( ex3d_rotating_cube ) ## OK
# add_subdirectory( ex3d_rotating_cubes ) ## OK
