cmake_minimum_required(VERSION 3.16)
project(examples_3d LANGUAGES CXX)



# add_subdirectory( ex3d_ecs ) ## X
# add_subdirectory( ex3d_ecs_boids ) ## X
# add_subdirectory( ex3d_ecs_collisions ) ## X


# add_subdirectory( ex3d_ecs_rendering_static_count ) ## X
# add_subdirectory( ex3d_ecs_rendering_dynamic_count ) ## X

# add_subdirectory( ex3d_collision_tree ) ## X
# add_subdirectory( ex3d_camera_controls ) ## X
# add_subdirectory( ex3d_circle ) ## X
# add_subdirectory( ex3d_circles ) ## X
add_subdirectory( ex3d_rotating_cube ) ## OK
# add_subdirectory( ex3d_rotating_cubes ) ## X
