# cmake_minimum_required(VERSION 3.16)
# project(examples_2d LANGUAGES CXX)


# add_subdirectory( ex2d_assets ) ## OK
# add_subdirectory( ex2d_camera ) ## X
# add_subdirectory( ex2d_canvas_paths ) ## OK
# # add_subdirectory( ex2d_fails ) ## X
# add_subdirectory( ex2d_flexLayout ) ## OK
# add_subdirectory( ex2d_gradients ) ## OK
# add_subdirectory( ex2d_images ) ## OK
# add_subdirectory( ex2d_inputs ) ## Somewhat works
# add_subdirectory( ex2d_keys ) ## OK
# add_subdirectory( ex2d_motions ) ## OK
# add_subdirectory( ex2d_mouse ) ## X
# add_subdirectory( ex2d_openmp_check ) ## Somewhat works
# add_subdirectory( ex2d_os_paths ) ## OK
# add_subdirectory( ex2d_position ) ## OK
# add_subdirectory( ex2d_property ) ## OK
# add_subdirectory( ex2d_reactive ) ## X
# add_subdirectory( ex2d_rounded ) ## OK





add_subdirectory( ex2d_sample ) ## X
# add_subdirectory( ex2d_sml ) ## X
# add_subdirectory( ex2d_texts ) ## X
# add_subdirectory( ex2d_timer ) ## X
# add_subdirectory( ex2d_velocity ) ## X
# add_subdirectory( ex2d_z_sorting ) ## X


